### ISSUE TITLE
Confusion over built in vectors

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/r-tidyverse-intro#36]
Ep1.

> R comes with a few built in vectors containing useful sequences:

...

> ```
> pi
> [1] 3.141593
> ```
I find this section a bit confusing due to the terminology. 

1. Pi isn't a vector, 
2. but are any of these built in vectors, or built in functions which return vectors?

**Comment by mawds** [comment]
Good spot. I've edited.

On point 2: "These are implemented as variables in the base namespace taking appropriate values."  (from `?Constants`
