### ISSUE TITLE
in the introduction give a list of variable that the student should see at the time

### ISSUE THREAD

**Issue by gruel** [UoMResearchIT/r-tidyverse-intro#61]
In: "Managing your environment (self study)"

when you are doing:

ls()

The answer to that command at the time should be;

[1] "x"

and not the list of element in the lessons.

**Comment by mawds** [comment]
Good spot, and thanks for the PR.  
However, the `.md ` files are built from the `.Rmd` files, so changes made in them get overwritten.  I'll try and think of a way of fooling the build system to just show `x`

**Comment by mawds** [comment]
Fixed in  760b98a  - created a temporary environment and (silently) showed the contents of this
